# Generated by Django 4.1.7 on 2023-03-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scaley_valley', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chain',
            name='explorer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chain',
            name='image_uri',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
