# Generated by Django 4.1.7 on 2023-03-18 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scaley_valley', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chain',
            name='indexed_blocks_interval',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chain',
            name='last_indexed_block',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kind',
            name='supply',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=80),
        ),
        migrations.CreateModel(
            name='NFTMintRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=42)),
                ('price', models.DecimalField(decimal_places=0, max_digits=256)),
                ('nft_id', models.DecimalField(decimal_places=0, max_digits=256)),
                ('mint_tx_hash', models.CharField(max_length=66)),
                ('purchase_tx_hash', models.CharField(max_length=66, unique=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('SENT', 'Sent'), ('SUCCESS', 'Success'), ('FAIL', 'Fail')], max_length=255)),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mint_requests', to='scaley_valley.kind')),
            ],
        ),
    ]
