# Generated by Django 4.1.7 on 2023-03-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scaley_valley', '0002_chain_indexed_blocks_interval_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nftmintrequest',
            name='mint_tx_hash',
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
        migrations.AlterField(
            model_name='nftmintrequest',
            name='nft_id',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=256, null=True),
        ),
    ]
