# Generated by Django 4.1.7 on 2023-03-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scaley_valley', '0003_alter_nftmintrequest_mint_tx_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kind',
            name='contract_kind_id',
            field=models.DecimalField(decimal_places=0, max_digits=80, unique=True),
        ),
    ]
