# Generated by Django 4.1.7 on 2023-03-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scaley_valley', '0004_alter_kind_contract_kind_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nftmintrequest',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('APPLIED', 'Applied in TradeContract'), ('SUCCESS', 'Success'), ('FAIL', 'Fail')], max_length=255),
        ),
    ]
