# Generated by Django 4.1.7 on 2023-03-20 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scaley_valley', '0005_alter_nftmintrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=256),
        ),
        migrations.AlterField(
            model_name='nftmintrequest',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('SUCCESS', 'Success'), ('FAIL', 'Fail'), ('APPLIED', 'Applied in TradeContract')], max_length=255),
        ),
    ]
