# Generated by Django 4.1.7 on 2023-03-20 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scaley_valley', '0006_resource_price_alter_nftmintrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='buy_resource_chain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buy_resource_chain', to='scaley_valley.chain'),
        ),
    ]
