# Generated by Django 4.1.7 on 2023-03-20 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scaley_valley', '0007_resource_buy_resource_chain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='chain',
            new_name='spend_resource_chain',
        ),
    ]
