# Generated by Django 4.1.7 on 2023-03-20 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scaley_valley', '0008_rename_chain_resource_spend_resource_chain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='resource_token_address',
            new_name='spendable_resource_token_address',
        ),
    ]
