# Generated by Django 4.1.7 on 2023-03-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scaley_valley', '0010_resource_buyable_resource_token_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='valley',
            name='collateral_address',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
        migrations.AddField(
            model_name='valley',
            name='collection_address',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
    ]
