# Generated by Django 4.1.7 on 2023-03-21 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scaley_valley', '0011_valley_collateral_address_valley_collection_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='kind',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=256, null=True),
        ),
    ]
