# Generated by Django 4.1.7 on 2023-03-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scaley_valley', '0012_kind_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='GnosisBridgeProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_tx_hash', models.CharField(max_length=66, unique=True)),
                ('bridge_l1_tx_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('PROCESS', 'Process'), ('SUCCESS', 'Success'), ('FAIL', 'Fail')], default='NEW', max_length=255)),
            ],
        ),
    ]
